# Generated by Django 3.1.4 on 2021-04-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=400)),
                ('connection_type', models.CharField(choices=[('connectiontype1', 'connectiontype1'), ('connectiontype2', 'connectiontype2'), ('connectiontype3', 'connectiontype3')], max_length=20)),
                ('router', models.CharField(choices=[('router1', 'router1'), ('router2', 'router2'), ('router3', 'router3')], max_length=20)),
                ('plan', models.CharField(choices=[('plan1', 'plan1'), ('plan2', 'plan2'), ('plan3', 'plan3')], max_length=20)),
                ('mobile1', models.IntegerField(max_length=10)),
                ('mobile2', models.IntegerField(max_length=10)),
            ],
        ),
    ]
