# Generated by Django 3.1.4 on 2021-05-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(default='admin@ithreesystem.com', max_length=100)),
                ('primary_mobile', models.IntegerField(default=0)),
                ('alternate_mobile', models.IntegerField(default=0)),
                ('address', models.CharField(default='Jejuri', max_length=400)),
                ('city', models.CharField(default='Jejuri', max_length=10)),
                ('state', models.CharField(default='Maharashtra', max_length=15)),
                ('zipcode', models.IntegerField(blank=True, default=0)),
                ('connection_type', models.CharField(default='not selected', max_length=20)),
                ('cat_6_cable_length', models.IntegerField()),
                ('p2p_device_price', models.IntegerField()),
                ('wireless_router_price', models.IntegerField(null=True)),
                ('ftth_fiber_length', models.IntegerField()),
                ('closer_box', models.CharField(max_length=5)),
                ('patch_cord', models.IntegerField()),
                ('ftth_router_price', models.IntegerField()),
                ('installation_charges', models.IntegerField(default=0)),
                ('username', models.CharField(default='username', max_length=10)),
                ('password', models.CharField(default='password', max_length=10)),
                ('customer_photo', models.ImageField(blank=True, default='', upload_to='customers/images')),
                ('kYC_document', models.ImageField(blank=True, default='', upload_to='customers/images')),
            ],
        ),
    ]
