# Generated by Django 3.1.4 on 2021-04-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile1',
            new_name='primary_mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile2',
        ),
        migrations.AddField(
            model_name='customer',
            name='alternate_mobile',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
