# Generated by Django 3.1.4 on 2021-06-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210613_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_photo',
            field=models.ImageField(blank=True, upload_to='customers/images'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kYC_document',
            field=models.ImageField(blank=True, upload_to='customers/images'),
        ),
    ]
