# Generated by Django 4.0.1 on 2022-01-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='admin@ithreesystem.com', max_length=100)),
                ('primary_mobile', models.IntegerField(blank=True, default=0)),
                ('alternate_mobile', models.IntegerField(blank=True, default=0)),
                ('address', models.CharField(default='Jejuri', max_length=400)),
                ('city', models.CharField(default='Jejuri', max_length=10)),
                ('state', models.CharField(default='Maharashtra', max_length=15)),
                ('zipcode', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
