# Generated by Django 4.0.1 on 2022-01-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cat_cable_length',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
