# Generated by Django 4.0.1 on 2022-01-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customer_cat_cable_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cat_cable_length',
            field=models.IntegerField(),
        ),
    ]
