# Generated by Django 4.0.1 on 2022-01-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customer_cat_cable_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='device_price',
            field=models.IntegerField(default=0),
        ),
    ]
