# Generated by Django 4.0.1 on 2022-01-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_device_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='device_price',
            new_name='p2p_device_price',
        ),
        migrations.AddField(
            model_name='customer',
            name='wireless_router_price',
            field=models.IntegerField(default=0),
        ),
    ]
