# Generated by Django 4.0.1 on 2022-01-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customer_closer_box_customer_ftth_fiber_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='installation_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pass', max_length=400),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='user', max_length=400),
        ),
    ]
