# Generated by Django 4.0.1 on 2022-01-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customer_installation_charges_customer_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='customer',
            name='kyc_doc',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
